### ISSUE TITLE
Is ready and complete use repositories

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/documentation#10]
Is ready and complete use repositories

Tnks

**Comment by ablanco** [comment]
The packages haven't been released yet. But you can find the development preview here: http://openmooc.org/openmooc-rpms/

**Comment by johnfelipe** [comment]
But in this moment how upgrade all in my instance

**Comment by pitbulk** [comment]
The documentation will be published, but we don't have an estimated date.

**Comment by johnfelipe** [comment]
I cant upgrade moocng, idp and askbot? (latest version no repos)
So i need build other instance with repos?

Tnks

**Comment by pitbulk** [comment]
Yes, you need to use a new environment.

If you backup the databases you will be able to migrate them to the new
environment later.

**Comment by johnfelipe** [comment]
But repos is not complete, when is ready

**Comment by johnfelipe** [comment]
I can create a complete instance with actual repos?

Tnks
