### ISSUE TITLE
About change pasword in all instances

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/documentation#11]
Hi, please tell me how change password in all instances i use openmooc apache version

**Comment by ablanco** [comment]
https://docs.djangoproject.com/en/1.4/topics/auth/#changing-passwords

**Comment by johnfelipe** [comment]
But ldap, simplesaml, cron, admin user django?

**Comment by ablanco** [comment]
Those are existing components that we are using, so you'll have to look for the specific methods in each component documentation.
