### ISSUE TITLE
Errores

### ISSUE THREAD

**Issue by gjpinerosm** [OpenMOOC/documentation#12]
Hola

De ante mano les agradezco mucho la colaboración que me puedan brindar. Desde Bogotá, Colombia, estamos muy interesados en poder trabajar sobre esta plataforma.

Desde hace varios días estoy intentando instalar esta plataforma, he seguido los pasos que estàn poublicados en la documentaciòn pero no he logrado conseguirlo. :_(

Estoy trabajando en un servidor CentOS 6.5.

Tengo algunos problemas como el siguient

Al ejecutar el comando “easy_install moocng”, me ha arrojado errores como este:

(moocng)[root@giovanni Descargas]# easy_install moocng
Searching for moocng
Reading https://pypi.python.org/simple/moocng/
Couldn’t find index page for ‘moocng’ (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
No local packages or download links found for moocng
error: Could not find suitable distribution for Requirement.parse(‘moocng’)

Y cuando he intenado instalar IDP, tampoco ha sido posible, arroja lo siguiente:

yum install openmooc-idp-nginx
Loaded plugins: fastestmirror, refresh-packagekit, security
Loading mirror speeds from cached hostfile
- base: mirror.espoch.edu.ec
- epel: mirror.us.leaseweb.net
- extras: mirror.espoch.edu.ec
- updates: mirror.espoch.edu.ec
  Setting up Install Process
  No package openmooc-idp-nginx available.
  Error: Nothing to do

Quedo atento a cualquier ayuda que me puedan brindar.

**Comment by ablanco** [comment]
Hi Giovanni.

There isn't a release of OpenMOOC yet, so you won't find the moocng in the python package index. You should use the rpm deploy method instead.

There is a repository that you can use at http://openmooc.org/openmooc-rpms/readme.html
But, as I've said, those are development packages, use them at your own risk.

Regards.
