### ISSUE TITLE
Problem with virtual appliance

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/documentation#4]
Hi, in initial boot:

![virtualappliance1](https://f.cloud.github.com/assets/428820/504452/9bb7d8c6-bce9-11e2-9188-9a4f0b32765d.png)

but in ifconfig this:

![virtualappliance2](https://f.cloud.github.com/assets/428820/504460/c90219c2-bce9-11e2-88c8-d55f8860e538.png)

and my C:\Windows\System32\drivers\etc\hosts

```
192.168.13.131  questions.example.com   mooc.example.com    idp.example.com
```

but not working:

![virtualappliance3](https://f.cloud.github.com/assets/428820/504472/080e8a60-bcea-11e2-8789-112ba35ccbf1.png)

**Comment by pitbulk** [comment]
You need a DHCP server in your network.

**Comment by johnfelipe** [comment]
It work in virtual box, not working in vmware workstation
