### ISSUE TITLE
Documentation for update all instances

### ISSUE THREAD

**Issue by johnfelipe** [OpenMOOC/documentation#5]
Hi please share a documentation for install all instances with new realeses, IDP, MOOCNG, QUESTIONS

Tnks

**Comment by johnfelipe** [comment]
Hi, i cant install with success my openmooc with all instance, please tell me command for this

Tnks

**Comment by ablanco** [comment]
Until we have a stable release we recommend to use the appliance (virtual machine). When the release is done, it will be easier to deploy, there will be rpms.
