### ISSUE TITLE
documentation disapeared

### ISSUE THREAD

**Issue by ytabaa** [OpenMOOC/documentation#6]
Dear "OpenMOOC"ers
This link https://github.com/OpenMOOC/documentation/blob/master/demostrator.rst
does not work ,please guide us towards the right one.
Thanks

**Comment by oscarcp** [comment]
Hi Yassine,

The OpenMOOC docs have been moved into the source/ directory inside that
repository so they can be generated with sphinx.

You can find it here:
https://github.com/OpenMOOC/documentation/blob/master/source/demostrator.rst

Regards,
Oscar

Dear "OpenMOOC"ers
This link
https://github.com/OpenMOOC/documentation/blob/master/demostrator.rst
does not work ,please guide us towards the right one.
Thanks

—
Reply to this email directly or view it on
GitHubhttps://github.com/OpenMOOC/documentation/issues/6
.

**Comment by ytabaa** [comment]
Thanks

2013/6/12 Oscar Carballal notifications@github.com
