### ISSUE TITLE
Missing repositories openmooc

### ISSUE THREAD

**Issue by lvelezsantos** [OpenMOOC/documentation#8]
Missing repositories openmooc.

**Comment by ablanco** [comment]
Care to explain? I don't know what you are talking about?

**Comment by lvelezsantos** [comment]
in the documentation on the part of the centos repositories added, not the command to add openmooc repositories. and most of the documentations is based on these repositories. That is what is missing and therefore I have problems in implementing

https://github.com/OpenMOOC/documentation/blob/master/source/install/repositories.rst

**Comment by ablanco** [comment]
The OpenMOOC rpm repository hasn't been officially released.

You can find the repository with the current packages here: http://openmooc.org/openmooc-rpms/readme.html

You can use that repository, but I recommend to wait for the stable release of the rpms.
